import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000',
        alignItems: 'center',
        justifyContent: 'flex-start',
        paddingTop: 50,
    },
    header: {
        marginTop: 50,
    },
    title: {
        color: '#fff',
        fontSize: 32,
        textAlign: 'center',
        marginBottom: 15,
    },
    placeholder: {
        width: 320,
        height: 50,
        backgroundColor: '#E0BB00',
        borderColor: '#69665b',
        borderWidth: 2,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        paddingHorizontal: 10,
    },
    inputText: {
        flex: 1,
        width: '100%',
        borderWidth: 0,
        borderBottomWidth: 0,
        outlineStyle: 'none'
    },
    icon: {
        marginRight: 8,
    },
    createNote: {
        width: 70,
        height: 70,
        backgroundColor: '#E0BB00',
        borderRadius: 35,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
    },
    addButton: {
        position: 'absolute',
        bottom: 130,
        right: 30,
    },
    arrowBack: {
        width: '100%',
        marginRight: -20,
    },
    noteHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        width: '100%',
        paddingHorizontal: 20,
        marginBottom: 20,
    },
    noteTitleInput: {
        flex: 1,
        marginLeft: 10,
        fontSize: 20,
        fontWeight: 'bold',
        color: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#555',
        paddingVertical: 4,
    },
    noteContainer: {
        width: 320,
        height: 500,
        backgroundColor: '#A9A4A4',
        borderColor: '#69665b',
        borderWidth: 2,
        borderRadius: 10,
        padding: 15,
    },
    noteDate: {
        color: '#fff',
        fontSize: 14,
        marginBottom: 10,
    },
    noteContent: {
        color: '#000',
        fontSize: 16,
        lineHeight: 22,
        width: '100%',
        textAlignVertical: 'top',
    },
    noteCard: {
        width: 320,
        backgroundColor: '#aaa',
        padding: 10,
        borderRadius: 8,
        marginBottom: 10,
    },
    noteInput: {
        flex: 1,
        width: '100%',
        fontSize: 16,
        color: '#000',
        lineHeight: 22,
        textAlignVertical: 'top',
        borderWidth: 0,
        borderBottomWidth: 0,
        outlineStyle: 'none',
    },
    cardTitle: {
        fontWeight: 'bold',
        fontSize: 16,
        marginBottom: 4,
        color: '#000',
    },
    cardSnippet: {
        fontSize: 14,
        color: '#333',
    },
});
